
version: '3.0'
services:
  web:
    image: tomsia1/io-lab-docker-ci-public:v1.0
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    # TODO: image, ports and redis dependency
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.